services:
  sci-stars:
    container_name: sci-stars
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
      - "7000:7000"
      - "7001:7001"
    tty: true
    restart: "on-failure"
